### ISSUE TITLE
ASPX sample, if it can be implemented

### ISSUE THREAD

**Issue by LukanR** [DevExpress-Examples/how-to-use-excel-add-ins-in-the-spreadsheet-control-e5012#1]
do you have a ASPX working sample, if it can be implemented
Also and sorry for asking if it's out of the scope, but, can custom addins be added?
Thanks in advance

**Comment by CodeKarno** [comment]
@LukanR  The approach from this example requires running Microsoft® Excel® in background. It processes a custom add-in - SpreadsheetControl only displays the result. 
In the case of using ASPxSpreadsheet, the application is running on your IIS server. Use of this solution in these conditions means running Microsoft Excel on your web server for every user. In multi-user environment, this will definitely take a lot of system resources, that's why we don't recommend this approach.
If you have further questions, please submit a ticket to our [Support Center](https://www.devexpress.com/Support/Center/Question/List/1).

**Comment by LukanR** [comment]
Thank you for the prompt reply and clear answer.
